### ISSUE TITLE
CodeSystems not translated to oid's in ProvideAndRegister

### ISSUE THREAD

**Issue by oliveregger** [i4mi/MobileAccessGateway#124]
http://localhost:9770/xdstools/Xdstools2.html#SimMsgViewer:default__asbtsrr/rep/prb/2023_09_14_09_54_10_324

-MIMEBoundary112233445566778899
Content-Type: application/xop+xml; charset=UTF-8; type="application/soap+xml"
Content-Transfer-Encoding: binary
Content-ID: <doc0@ihexds.nist.gov>

<S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Header><wsa:Action xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:s="http://www.w3.org/2003/05/soap-envelope" s:mustUnderstand="1">urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-bResponse</wsa:Action><wsa:RelatesTo xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:uuid:2de3474d-70a7-4287-a0e0-82843cb7795d</wsa:RelatesTo></S:Header><S:Body><rs:RegistryResponse xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure"><rs:RegistryErrorList><rs:RegistryError codeContext="DocumentEntry(urn:uuid:1e404af3-077f-4bee-b7a6-a9be97e1ce01): the code http://ihe.net/fhir/ihe.formatcode.fhir/CodeSystem/formatcode(urn:ihe:pcc:cm:2008) is not found in the Affinity Domain configuration" errorCode="XDSRegistryMetadataError" location="CodeValidation" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error" /><rs:RegistryError codeContext="DocumentEntry(urn:uuid:1e404af3-077f-4bee-b7a6-a9be97e1ce01): the code http://loinc.org(34895-3) is not found in the Affinity Domain configuration" errorCode="XDSRegistryMetadataError" location="CodeValidation" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error" /><rs:RegistryError codeContext="DocumentEntry(urn:uuid:1e404af3-077f-4bee-b7a6-a9be97e1ce01): the code http://terminology.hl7.org/CodeSystem/v3-Confidentiality(N) is not found in the Affinity Domain configuration" errorCode="XDSRegistryMetadataError" location="CodeValidation" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error" /></rs:RegistryErrorList></rs:RegistryResponse></S:Body></S:Envelope>

**Comment by oliveregger** [comment]
<rs:RegistryError codeContext="DocumentEntry(urn:uuid:1e404af3-077f-4bee-b7a6-a9be97e1ce01): the code http://ihe.net/fhir/ihe.formatcode.fhir/CodeSystem/formatcode(urn:ihe:pcc:cm:2008) is not found in the Affinity Domain configuration" errorCode="XDSRegistryMetadataError" location="CodeValidation" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error" />
        <rs:RegistryError codeContext="DocumentEntry(urn:uuid:1e404af3-077f-4bee-b7a6-a9be97e1ce01): the code http://loinc.org(34895-3) is not found in the Affinity Domain configuration" errorCode="XDSRegistryMetadataError" location="CodeValidation" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error" />
        <rs:RegistryError codeContext="DocumentEntry(urn:uuid:1e404af3-077f-4bee-b7a6-a9be97e1ce01): the code http://terminology.hl7.org/CodeSystem/v3-Confidentiality(N) is not found in the Affinity Domain configuration" errorCode="XDSRegistryMetadataError" location="CodeValidation" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error" />

**Comment by oliveregger** [comment]
http://ihe.net/fhir/ihe.formatcode.fhir/CodeSystem/formatcode -> 1.3.6.1.4.1.19376.1.2.3
http://loinc.org -> 2.16.840.1.113883.6.1
http://terminology.hl7.org/CodeSystem/v3-Confidentiality -> 2.16.840.1.113883.5.25

**Comment by Alexander-Kreutz** [comment]
fixed with https://github.com/i4mi/MobileAccessGateway/commit/2d2eb24b92743c21211102dadd71d094ed00ab4e
