### ISSUE TITLE
pixm: http error code 404 instead of 400 for sourceIdentifier Assigning Authority not found

### ISSUE THREAD

**Issue by oliveregger** [i4mi/MobileAccessGateway#54]
GET https://test.ahdis.ch/mag-pmp/fhir/Patient/$ihe-pix?sourceIdentifier=urn%3Aoid%3A2.16.756.5.30.1.196.3.2.1%7CBADPATIENT001&targetSystem=urn%3Aoid%3A2.16.756.5.30.1.127.3.10.3 HTTP/1.1

return HTTP error 400

For this specific request, the 404 is correct, the detailed message is sourceIdentifier Assigning Authority not found
and according to https://profiles.ihe.net/ITI/PIXm/ITI-83.html#23834223-source-domain-not-recognized this should
be returned with an OperationOutcome and 404 (there are others with 400 and 403).

**Comment by Alexander-Kreutz** [comment]
Please recheck the spec (at the above provided link). For the Assigning Authority domain not found case error 400 is correct. For patient identifier not found it is 404.

**Comment by oliveregger** [comment]
{
  "response": {
    "status": 400,
    "data": {
      "resourceType": "OperationOutcome",
      "issue": [
        {
          "severity": "error",
          "code": "invalid",
          "diagnostics": "The ID number \"MAGMED010\" is not recognized by the MPI!"
        }
      ]
    }
  },
  "config": {
    "method": "GET",
    "url": "https://test.ahdis.ch/mag-pmp/fhir/Patient/$ihe-pix?sourceIdentifier=urn:oid:2.16.756.5.30.1.196.3.2.1|MAGMED010&targetSystem=urn:oid:2.16.756.5.30.1.191.1.0.2.1&targetSystem=urn:oid:2.16.756.5.30.1.127.3.10.3",
    "headers": {}
  }
}

**Comment by Alexander-Kreutz** [comment]
Behavior is according to specification.
