### ISSUE TITLE
NP for fhir/metadata with latest version

### ISSUE THREAD

**Issue by oliveregger** [i4mi/MobileAccessGateway#56]
@host = http://localhost:9090/mag-pmp

###
GET {{host}}/fhir/metadata
Accept: application/fhir+json

returns:
Caused by: java.lang.NullPointerException: null
        at ca.uhn.fhir.rest.server.RestfulServerConfiguration.collectMethodBindings(RestfulServerConfiguration.java:359) ~[hapi-fhir-server-5.4.2.jar:na]
        at ca.uhn.fhir.rest.server.RestfulServerConfiguration.provideBindings(RestfulServerConfiguration.java:252) ~[hapi-fhir-server-5.4.2.jar:na]
        at ca.uhn.fhir.rest.server.provider.ServerCapabilityStatementProvider.getServerConformance(ServerCapabilityStatementProvider.java:194) ~[hapi-fhir-server-5.4.2.jar:na]
        ... 144 common frames omitte

**Comment by oliveregger** [comment]
HTTP/1.1 500 Server Error
Connection: close
Date: Fri, 17 Sep 2021 15:45:14 GMT
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
X-Powered-By: HAPI FHIR 5.4.2 REST Server (FHIR Server; FHIR 4.0.1/R4)
X-Request-ID: RVBoDaVqdmgY58bM
Content-Type: application/fhir+json;charset=utf-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Server: Jetty(9.4.43.v20210629)

{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: java.lang.NullPointerException"
    }
  ]
}

**Comment by oliveregger** [comment]
ca.uhn.fhir.rest.server.RestfulServerConfiguration

	public Map<String, List<BaseMethodBinding<?>>> collectMethodBindings() {
		Map<String, List<BaseMethodBinding<?>>> resourceToMethods = new TreeMap<>();
L359		for (ResourceBinding next : getResourceBindings()) {

**Comment by oliveregger** [comment]
metadata on 5.2.0

{
  "resourceType": "CapabilityStatement",
  "status": "active",
  "date": "2021-09-27T18:28:53+00:00",
  "publisher": "Not provided",
  "kind": "instance",
  "software": {
    "name": "HAPI FHIR Server",
    "version": "5.2.0"
  },
  "implementation": {
    "description": "HAPI FHIR",
    "url": "http://10.28.2.4/mag-pmp/fhir"
  },
  "fhirVersion": "4.0.1",
  "format": [
    "application/fhir+xml",
    "application/fhir+json"
  ],
  "rest": [
    {
      "mode": "server",
      "resource": [
        {
          "type": "DocumentReference",
          "profile": "http://hl7.org/fhir/StructureDefinition/DocumentReference",
          "interaction": [
            {
              "code": "read"
            },
            {
              "code": "vread"
            },
            {
              "code": "search-type"
            }
          ],
          "searchParam": [
            {
              "name": "patient",
              "type": "reference",
              "documentation": "Who/what is the subject of the document"
            },
            {
              "name": "_id",
              "type": "token",
              "documentation": "The ID of the resource"
            },
            {
              "name": "author",
              "type": "reference",
              "documentation": "Who and/or what authored the document"
            },
            {
              "name": "category",
              "type": "token",
              "documentation": "Categorization of document"
            },
            {
              "name": "class",
              "type": "token"
            },
            {
              "name": "date",
              "type": "date",
              "documentation": "When this document reference was created"
            },
            {
              "name": "event",
              "type": "token",
              "documentation": "Main clinical acts documented"
            },
            {
              "name": "facility",
              "type": "token",
              "documentation": "Kind of facility where patient was seen"
            },
            {
              "name": "format",
              "type": "token",
              "documentation": "Format/content rules for the document"
            },
            {
              "name": "identifier",
              "type": "token",
              "documentation": "Master Version Specific Identifier"
            },
            {
              "name": "indexed",
              "type": "date"
            },
            {
              "name": "period",
              "type": "date",
              "documentation": "Time of service that is being documented"
            },
            {
              "name": "related",
              "type": "reference",
              "documentation": "Related identifiers or resources"
            },
            {
              "name": "related-id",
              "type": "token"
            },
            {
              "name": "security-label",
              "type": "token",
              "documentation": "Document security-tags"
            },
            {
              "name": "securitylabel",
              "type": "token"
            },
            {
              "name": "setting",
              "type": "token",
              "documentation": "Additional details about where the content was created (e.g. clinical specialty)"
            },
            {
              "name": "status",
              "type": "token",
              "documentation": "current | superseded | entered-in-error"
            },
            {
              "name": "type",
              "type": "token",
              "documentation": "Kind of document (LOINC if possible)"
            }
          ]
        },
        {
          "type": "List",
          "profile": "http://hl7.org/fhir/StructureDefinition/ListResource",
          "interaction": [
            {
              "code": "read"
            },
            {
              "code": "vread"
            },
            {
              "code": "search-type"
            }
          ],
          "searchParam": [
            {
              "name": "patient",
              "type": "reference",
              "documentation": "If all resources have the same subject"
            },
            {
              "name": "status",
              "type": "token",
              "documentation": "current | retired | entered-in-error"
            },
            {
              "name": "ListResource",
              "type": "token"
            },
            {
              "name": "_id",
              "type": "token",
              "documentation": "The ID of the resource"
            },
            {
              "name": "code",
              "type": "token",
              "documentation": "What the purpose of this list is"
            },
            {
              "name": "date",
              "type": "date",
              "documentation": "When the list was prepared"
            },
            {
              "name": "identifier",
              "type": "token",
              "documentation": "Business identifier"
            },
            {
              "name": "source",
              "type": "reference",
              "documentation": "Who and/or what defined the list contents (aka Author)"
            }
          ]
        },
        {
          "type": "OperationDefinition",
          "profile": "http://hl7.org/fhir/StructureDefinition/OperationDefinition",
          "interaction": [
            {
              "code": "read"
            }
          ]
        },
        {
          "type": "Patient",
          "profile": "http://hl7.org/fhir/StructureDefinition/Patient",
          "interaction": [
            {
              "code": "read"
            },
            {
              "code": "vread"
            },
            {
              "code": "search-type"
            }
          ],
          "searchParam": [
            {
              "name": "_id",
              "type": "token",
              "documentation": "The ID of the resource"
            },
            {
              "name": "active",
              "type": "token",
              "documentation": "Whether the patient record is active"
            },
            {
              "name": "address",
              "type": "string",
              "documentation": "A server defined search that may match any of the string fields in the Address, including line, city, district, state, country, postalCode, and/or text"
            },
            {
              "name": "address-city",
              "type": "string",
              "documentation": "A city specified in an address"
            },
            {
              "name": "address-country",
              "type": "string",
              "documentation": "A country specified in an address"
            },
            {
              "name": "address-postalcode",
              "type": "string",
              "documentation": "A postalCode specified in an address"
            },
            {
              "name": "address-state",
              "type": "string",
              "documentation": "A state specified in an address"
            },
            {
              "name": "birthdate",
              "type": "date",
              "documentation": "The patient's date of birth"
            },
            {
              "name": "family",
              "type": "string",
              "documentation": "A portion of the family name of the patient"
            },
            {
              "name": "gender",
              "type": "token",
              "documentation": "Gender of the patient"
            },
            {
              "name": "given",
              "type": "string",
              "documentation": "A portion of the given name of the patient"
            },
            {
              "name": "identifier",
              "type": "token",
              "documentation": "Logical id of this artifact"
            },
            {
              "name": "mothersMaidenName",
              "type": "string"
            },
            {
              "name": "telecom",
              "type": "string",
              "documentation": "The value in any kind of telecom details of the patient"
            }
          ]
        }
      ],
      "interaction": [
        {
          "code": "transaction"
        }
      ],
      "operation": [
        {
          "name": "process-message",
          "definition": "http://10.28.2.4/mag-pmp/fhir/OperationDefinition/-s-process-message"
        },
        {
          "name": "find-medication-list",
          "definition": "http://10.28.2.4/mag-pmp/fhir/OperationDefinition/DocumentReference-i-find-medication-list"
        },
        {
          "name": "ihe-pix",
          "definition": "http://10.28.2.4/mag-pmp/fhir/OperationDefinition/Patient-i-ihe-pix"
        }
      ]
    }
  ]
}

metadata on 5.5.1 after fixing NP:
{
  "resourceType": "CapabilityStatement",
  "id": "900f6134-bb79-4c6a-ae5c-a35ff26b22f7",
  "name": "RestServer",
  "status": "active",
  "date": "2021-09-27T20:26:38.667+02:00",
  "publisher": "Not provided",
  "kind": "instance",
  "software": {
    "name": "HAPI FHIR",
    "version": "5.5.1"
  },
  "implementation": {
    "description": "HAPI FHIR",
    "url": "http://test.ahdis.ch/mag-pmp/fhir"
  },
  "fhirVersion": "4.0.1",
  "format": [
    "application/fhir+xml",
    "xml",
    "application/fhir+json",
    "json",
    "html/json",
    "html/xml"
  ],
  "rest": [
    {
      "mode": "server"
    }
  ]
}

**Comment by unixoid** [comment]
Upgrade to HAPI FHIR 5.7.2 (see https://github.com/ahdis/MobileAccessGateway/tree/20220502-unixoid-IPF_4.3.1) seems to solve the issue.

**Comment by Alexander-Kreutz** [comment]
fixed with HAPI 5.7.2
